name: Build APK - AIDL Fix

on:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-20.04  # Version LTS stable
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Setup Java JDK 8 (requis pour Android)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-8-jdk python3-pip autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev \
            libtinfo5 cmake libffi-dev libssl-dev
          
      - name: Install Buildozer with fixed versions
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer==1.4.0
          pip3 install cython==0.29.33
          
      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          
      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          echo 'count=0' > ~/.android/repositories.cfg
          
      - name: Build APK
        run: |
          # Accepter toutes les licences Android automatiquement
          yes | buildozer android debug || buildozer android debug
        env:
          ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
          ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bcc-control-apk
          path: bin/*.apk
