name: Build APK - AIDL Fix
on:
  push:
    branches: [ main, master ]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-22.04  # ✅ Version supportée (ubuntu-20.04 est dépréciée)
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5  # ✅ Version mise à jour
        with:
          python-version: '3.9'
          
      - name: Setup Java JDK 8 (requis pour Android)
        uses: actions/setup-java@v4  # ✅ Version mise à jour
        with:
          distribution: 'temurin'
          java-version: '8'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-8-jdk python3-pip autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev \
            libtinfo5 cmake libffi-dev libssl-dev
          
      - name: Install Buildozer with fixed versions
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer==1.5.0  # ✅ Version plus récente et stable
          pip3 install cython==0.29.36   # ✅ Version mise à jour
          
      - name: Cache Buildozer dependencies
        uses: actions/cache@v4  # ✅ Version mise à jour
        with:
          path: |
            ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          
      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          echo 'count=0' > ~/.android/repositories.cfg
          
      - name: Build APK
        run: |
          # Configuration des variables d'environnement avant le build
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          # Build avec gestion d'erreur améliorée
          buildozer android debug || (echo "Build failed, retrying..." && buildozer android debug)
        env:
          ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
          ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bcc-control-apk
          path: bin/*.apk
        if: always()  # ✅ Upload même si des étapes précédentes ont échoué
