name: Build APK Simple
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-20.04  # Version plus stable pour buildozer
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Setup Java 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk autoconf libtool
        sudo apt-get install -y build-essential libffi-dev
    
    - name: Install buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.4.0 cython==0.29.33
    
    - name: Create basic buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = BCC Control
        package.name = bcccontrol  
        package.domain = org.ceet.bcc
        source.dir = .
        version = 1.0
        requirements = python3,kivy
        icon.filename = CEET.png
        orientation = portrait

        [buildozer]
        log_level = 2

        [android]
        api = 27
        minapi = 21
        ndk = 19b
        android.accept_sdk_license = True
        android.orientation = portrait
        android.icon = CEET.png
        android.archs = armeabi-v7a
        android.permissions = INTERNET
        EOF
    
    - name: Build APK
      run: |
        yes | buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk
